# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_hub', '0004_auto_20161114_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='widget_type',
            field=models.CharField(choices=[('CHT', 'Chart'), ('MTC', 'Metric'), ('IND', 'indicator'), ('BUTN', 'Button')], default='CHT', max_length=3),
        ),
    ]
